/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import javax.swing.JOptionPane;

/**
 *
 * @author luan
 */
public class tela_Compra_Cliente extends javax.swing.JFrame {

    /**
     * Creates new form tela_Compra
     */
    public tela_Compra_Cliente() {
        initComponents();
    }
    
    boolean checkVazio() {
        boolean vazio;
        
        if(emailInput.getText().equals("") ||
           celularInput.getText().equals("(  )       -     ") ||
           numeroCartaoInput.getText().equals("") ||
           cvvInput.getText().equals("") || 
           enderecoInput.getText().equals("") || 
           cepInput.getText().equals("     -   ") || 
           nomeTitularInput.getText().equals("") || 
           cpfInput.getText().equals("   .   .   -  ") || 
           dataVencimentoInput.getText().equals("  /  ")){
            
            vazio = true;
            
        } else {
            
            vazio = false;
        }
        
        return vazio;
    };

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelBranco = new javax.swing.JPanel();
        icone = new javax.swing.JLabel();
        infoLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        emailInput = new javax.swing.JTextField();
        celularLabel = new javax.swing.JLabel();
        celularInput = new javax.swing.JFormattedTextField();
        dadosCartaoLabel = new javax.swing.JLabel();
        numeroCartaoLabel = new javax.swing.JLabel();
        numeroCartaoInput = new javax.swing.JTextField();
        cvvLabel = new javax.swing.JLabel();
        cvvInput = new javax.swing.JTextField();
        enderecoLabel = new javax.swing.JLabel();
        enderecoInput = new javax.swing.JTextField();
        cepLabel = new javax.swing.JLabel();
        cepInput = new javax.swing.JFormattedTextField();
        nomeTitularLabel = new javax.swing.JLabel();
        nomeTitularInput = new javax.swing.JTextField();
        cpfLabel = new javax.swing.JLabel();
        cpfInput = new javax.swing.JFormattedTextField();
        dataVencimentoLabel = new javax.swing.JLabel();
        dataVencimentoInput = new javax.swing.JFormattedTextField();
        finalizarCompraButton = new javax.swing.JButton();

        setTitle("FINALIZAR COMPRA");

        painelBranco.setBackground(new java.awt.Color(255, 255, 255));

        icone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Farmacia_Logo.png"))); // NOI18N

        infoLabel.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        infoLabel.setForeground(new java.awt.Color(0, 0, 0));
        infoLabel.setText("Informações de Pagamento:");

        emailLabel.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(0, 0, 0));
        emailLabel.setText("E-mail:");
        emailLabel.setToolTipText("");

        emailInput.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        emailInput.setForeground(new java.awt.Color(0, 0, 0));

        celularLabel.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        celularLabel.setForeground(new java.awt.Color(0, 0, 0));
        celularLabel.setText("Celular:");

        try {
            celularInput.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ##### - ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        dadosCartaoLabel.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        dadosCartaoLabel.setForeground(new java.awt.Color(0, 0, 0));
        dadosCartaoLabel.setText("Dados do Cartão:");

        numeroCartaoLabel.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        numeroCartaoLabel.setForeground(new java.awt.Color(0, 0, 0));
        numeroCartaoLabel.setText("Numero do Cartão:");

        numeroCartaoInput.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N

        cvvLabel.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        cvvLabel.setForeground(new java.awt.Color(0, 0, 0));
        cvvLabel.setText("CVV:");

        cvvInput.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        cvvInput.setForeground(new java.awt.Color(0, 0, 0));

        enderecoLabel.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        enderecoLabel.setForeground(new java.awt.Color(0, 0, 0));
        enderecoLabel.setText("Endereço:");

        enderecoInput.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        enderecoInput.setForeground(new java.awt.Color(0, 0, 0));

        cepLabel.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        cepLabel.setForeground(new java.awt.Color(0, 0, 0));
        cepLabel.setText("CEP:");

        try {
            cepInput.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        nomeTitularLabel.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        nomeTitularLabel.setForeground(new java.awt.Color(0, 0, 0));
        nomeTitularLabel.setText("Nome do Titular:");
        nomeTitularLabel.setToolTipText("");

        nomeTitularInput.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        nomeTitularInput.setForeground(new java.awt.Color(0, 0, 0));

        cpfLabel.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        cpfLabel.setForeground(new java.awt.Color(0, 0, 0));
        cpfLabel.setText("CPF do Titular:");

        try {
            cpfInput.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        dataVencimentoLabel.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        dataVencimentoLabel.setForeground(new java.awt.Color(0, 0, 0));
        dataVencimentoLabel.setText("Data de Vencimento:");

        try {
            dataVencimentoInput.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        finalizarCompraButton.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        finalizarCompraButton.setText("Finalizar Compra.");
        finalizarCompraButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizarCompraButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelBrancoLayout = new javax.swing.GroupLayout(painelBranco);
        painelBranco.setLayout(painelBrancoLayout);
        painelBrancoLayout.setHorizontalGroup(
            painelBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBrancoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dadosCartaoLabel)
                    .addGroup(painelBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(painelBrancoLayout.createSequentialGroup()
                            .addComponent(enderecoInput, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(cepInput, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(painelBrancoLayout.createSequentialGroup()
                            .addGroup(painelBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(painelBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(painelBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(emailInput)
                                        .addComponent(infoLabel))
                                    .addComponent(enderecoLabel))
                                .addComponent(emailLabel, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGap(18, 18, 18)
                            .addGroup(painelBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cepLabel)
                                .addComponent(celularLabel)
                                .addComponent(celularInput))))
                    .addComponent(numeroCartaoInput, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(painelBrancoLayout.createSequentialGroup()
                        .addComponent(numeroCartaoLabel)
                        .addGap(149, 149, 149)
                        .addComponent(cvvLabel))
                    .addGroup(painelBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelBrancoLayout.createSequentialGroup()
                            .addGap(267, 267, 267)
                            .addComponent(cvvInput, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(painelBrancoLayout.createSequentialGroup()
                            .addGroup(painelBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cpfLabel)
                                .addComponent(cpfInput, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(painelBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(dataVencimentoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dataVencimentoInput))))
                    .addComponent(nomeTitularLabel)
                    .addComponent(nomeTitularInput, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(painelBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelBrancoLayout.createSequentialGroup()
                        .addComponent(icone)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelBrancoLayout.createSequentialGroup()
                        .addComponent(finalizarCompraButton)
                        .addGap(48, 48, 48))))
        );
        painelBrancoLayout.setVerticalGroup(
            painelBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBrancoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(infoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(celularLabel)
                    .addComponent(emailLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(emailInput)
                    .addComponent(celularInput, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelBrancoLayout.createSequentialGroup()
                        .addGroup(painelBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(enderecoLabel)
                            .addComponent(cepLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(enderecoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cepInput, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(dadosCartaoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numeroCartaoLabel)
                            .addComponent(cvvLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numeroCartaoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cvvInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nomeTitularLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nomeTitularInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(finalizarCompraButton)))
                    .addComponent(icone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpfLabel)
                    .addComponent(dataVencimentoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpfInput, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataVencimentoInput, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelBranco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelBranco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void finalizarCompraButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizarCompraButtonActionPerformed
        if (!checkVazio()) {
            JOptionPane.showMessageDialog(null, "COMPRA REALIZADA COM SUCESSO!!!");
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "PORFAVOR PREENCHA TODOS OS CAMPOS.");
        }
    }//GEN-LAST:event_finalizarCompraButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela_Compra_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela_Compra_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela_Compra_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela_Compra_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela_Compra_Cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField celularInput;
    private javax.swing.JLabel celularLabel;
    private javax.swing.JFormattedTextField cepInput;
    private javax.swing.JLabel cepLabel;
    private javax.swing.JFormattedTextField cpfInput;
    private javax.swing.JLabel cpfLabel;
    private javax.swing.JTextField cvvInput;
    private javax.swing.JLabel cvvLabel;
    private javax.swing.JLabel dadosCartaoLabel;
    private javax.swing.JFormattedTextField dataVencimentoInput;
    private javax.swing.JLabel dataVencimentoLabel;
    private javax.swing.JTextField emailInput;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField enderecoInput;
    private javax.swing.JLabel enderecoLabel;
    private javax.swing.JButton finalizarCompraButton;
    private javax.swing.JLabel icone;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JTextField nomeTitularInput;
    private javax.swing.JLabel nomeTitularLabel;
    private javax.swing.JTextField numeroCartaoInput;
    private javax.swing.JLabel numeroCartaoLabel;
    private javax.swing.JPanel painelBranco;
    // End of variables declaration//GEN-END:variables
}
